/*
 * Created by Thomas Hartmann
 * Action types for user bookings
 */
export default {
  SET_BOOKING_DATE: 'SET_BOOKING_DATE',
  SET_BOOKING_TIME: 'SET_BOOKING_TIME',
  SET_BOOKING_BRANCH: 'SET_BOOKING_BRANCH',
  SET_CLIENT_NAME: 'SET_CLIENT_NAME',
  SET_CLIENT_EMAIL: 'SET_CLIENT_EMAIL',
  SELECT_PROPERTY: 'SELECT_PROPERTY'
}
