export const allBedroomValues = ['1', '2', '3+']

export default {
  ADD_COUNTY: 'ADD_COUNTY',
  REMOVE_COUNTY: 'REMOVE_COUNTY',
  MIN_PRICE: 'MIN_PRICE',
  MAX_PRICE: 'MAX_PRICE',
  MIN_SIZE: 'MIN_SIZE',
  MAX_SIZE: 'MAX_SIZE',
  ADD_BEDROOM_OPTION: 'ADD_BEDROOM_OPTION',
  REMOVE_BEDROOM_OPTION: 'REMOVE_BEDROOM_OPTION'
}
