export const allBedroomValues = ['1', '2', '3+']

export default {
  ADD_COUNTY: 'ADD_COUNTY',
  REMOVE_COUNTY: 'REMOVE_COUNTY',
  SET_MIN_PRICE: 'SET_MIN_PRICE',
  SET_MAX_PRICE: 'SET_MAX_PRICE',
  SET_MIN_SIZE: 'SET_MIN_SIZE',
  SET_MAX_SIZE: 'SET_MAX_SIZE',
  ADD_BEDROOM_OPTION: 'ADD_BEDROOM_OPTION',
  REMOVE_BEDROOM_OPTION: 'REMOVE_BEDROOM_OPTION'
}
