/*
 * @flow
 *  Created by Thomas Hartmann
 * This is a list of actions a user can perform on
 * the property filter
 */

export default {
    // property filtering
  ADD_COUNTY: 'ADD_COUNTY',
  REMOVE_COUNTY: 'REMOVE_COUNTY',
  SET_COUNTY: 'SET_COUNTY',
  CLEAR_COUNTIES: 'CLEAR_COUNTIES',

  SET_MIN_PRICE: 'SET_MIN_PRICE',
  SET_MAX_PRICE: 'SET_MAX_PRICE',

  // SET_NUMBER_OF_BEDROOMS
  ADD_BEDROOM_OPTION: 'ADD_BEDROOM_OPTION',
  REMOVE_BEDROOM_OPTION: 'REMOVE_BEDROOM_OPTION',
  CLEAR_BEDROOMS: 'CLEAR_BEDROOMS',

  SET_MIN_SIZE: 'SET_MIN_SIZE',
  SET_MAX_SIZE: 'SET_MAX_SIZE',

  CLEAR_FILTER: 'CLEAR_FILTER'
}
